import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { SidebarUse } from "../../components/sidebarUse";
import Header from "../../components/header";
import { Provider } from  "../../provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthentifiedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      // <Provider>
            <SidebarUse >
                <Header />
              {children}
            </SidebarUse>        
      // </Provider>
  );
}
